#!/usr/bin/env python3
"""Render a compact, standalone report from completed offline audit artifacts."""
import argparse,csv,html,json,pathlib
from audit import ROOT

def run(out):
 def load(name):return json.loads((out/name).read_text(encoding='utf-8-sig'))
 s=load('summary.json');g=load('grouping-summary.json')
 def esc(v):return html.escape(str(v))
 def link(file,label):return f'<a href="{esc(file)}">{esc(label)}</a>'
 def wiki(title,label=None):return f'<a href="https://oldschool.runescape.wiki/w/{title}">{esc(label or title.replace("_"," "))}</a>'
 def table(headers,rows):return '<table><thead><tr>'+''.join('<th>'+esc(c)+'</th>' for c in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(c)+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table>'
 domainrows=[]
 for d,count in g['domain_row_counts'].items():
  domainrows.append([esc(d),f'{count:,}',link('reviews/'+d+'/','Domain artifacts')])
 priorities=[
 ['Ammunition identity','32 javelin variants retain generic gear tags; seven brutal arrows fall through to cleanup; barbed bolt ID 881 falls into raw resources.','Use explicit projectile/weapon compatibility to propose ammunition membership. An ammo equipment slot also holds blessings, so it is insufficient alone.',wiki('Javelins')+'; '+wiki('Rune_brutal')+'; '+wiki('Barbed_bolts')],
 ['Farming stages','23 ordinary saplings are missing from the existing species families despite seed counterparts. There are 47 proposed Farming/material families.','Add exact seed-to-sapling stage edges; keep quest saplings and region-specific planting mechanics separate.',link('reviews/farming-materials/proposed-families.csv','Proposed families')+'; '+wiki('Sapling')],
 ['Dose-state families','134 sourced candidate families cover 466 IDs: 22 existing curated families and 112 more from explicit Wiki dose-version anchors.','Order dose states within each family, preserving each ID, special use, quest association and any area restriction.',link('reviews/supplies-herblore/group-candidates.json','Sourced dose and food groups')],
 ['Skilling outfit blocks','Documented outfits include Angler, Spirit Angler, Farmer, Carpenter, Zealot, Smiths’ Uniform, Golden Prospector and camouflage groups missing from explicit set coverage.','Add exact component/slot membership. Body styles, recolours and alternate gloves remain distinct states.',wiki('XP_clothing')+'; '+wiki('Smiths%27_Uniform')],
 ['Utility state and restrictions','Full article checks distinguish reusable storage, lit/unlit lighting, rune storage, obsolete tokens and moderator-only teleports.','Use state-specific function. Deadman teleport tablet is moderator-only; Survival token is obsolete. Spirit flakes require a Fishing-supply role review rather than currency from category membership alone.',link('reviews/utilities-containers/role-grouping-candidates.csv','Utility candidates')+'; '+link('reviews/utilities-containers/state-families.csv','17 utility state families')+'; '+wiki('Deadman_teleport_tablet')+'; '+wiki('Spirit_flakes')],
 ['Reward keys and components','Brimstone key ID 23083, Malediction shard 2 ID 11932 and Scurrius’ spine ID 28798 currently fall through to cleanup.','Propose reward-key or boss-component families while retaining opening/crafting mechanics and source activity.',link('reviews/loot-quests-clues/priority-cases.csv','13 source-checked priority cases')],
 ['Overlap policy','526 exact-ID page matches have an emote-clue requirement facet; 625 have Treasure Trails reward membership; 2,223 have Collection Log category membership.','Keep requirement, reward provenance, log membership and storage preference independent of practical use. Ranger boots can remain gear while carrying clue-reward and log provenance.',wiki('Ranger_boots')+'; '+wiki('Collection_log')],
 ]
 outputs=[('full-grouping-audit.csv','Complete per-item grouping audit'),('registry-universe.csv','All registry IDs and exclusion/null status'),('mechanical-findings.csv','Mechanical review signals'),('grouping-groups.csv','Exact-ID group inventory'),('grouping-edges.csv','Exact membership and ordering graph'),('recipe-workflow-edges.csv','All material/tool/facility recipe edges'),('wiki-version-family-candidates.csv','Explicit Wiki version pools, kept as candidates'),('unverified-family-candidates.csv','Weak family hints, clearly unverified'),('domain-evidence.jsonl','Unflattened domain evidence'),('reviews/coverage-variants/multi-match-candidates.csv','All 13 ambiguous-ID candidates'),('reviews/coverage-variants/outside-effective-wiki-matches.csv','161 exact Wiki matches outside effective export'),('reviews/coverage-variants/alternate-id-coverage.csv','Alternate ID links and namespace guard review'),('summary.json','Coverage and source limits'),('grouping-summary.json','Grouping counts and source hashes')]
 body=f'''<p class="eyebrow">BANK ARCHITECT · OFFLINE RESEARCH · 2 OCTOBER 2026</p><h1>Full semantic grouping analysis</h1>
 <p class="lead">The entire named preset universe has been mechanically analyzed by six GPT-6 Luna agents at high effort, with root review of joins, source scope and grouping policy. Exact Wiki item-ID evidence covers {s['counts']['EXACT_ID_SINGLE']+s['counts']['EXACT_ID_MULTIPLE']:,} of {s['counts']['effective_records']:,} named IDs. The remainder stays explicitly unresolved.</p>
 <div class="metrics"><div><b>{s['registry_rows']:,}</b><span>Registry IDs accounted for</span></div><div><b>{s['counts']['effective_records']:,}</b><span>Named preset items analyzed</span></div><div><b>{s['counts']['EXACT_ID_SINGLE']+s['counts']['EXACT_ID_MULTIPLE']:,}</b><span>Exact Wiki ID matches</span></div><div><b>{s['mechanically_flagged_distinct_items']:,}</b><span>Mechanically flagged items</span></div></div>
 <p><strong>These are review candidates, not a count of confirmed bugs.</strong> Production classifications and live account settings were not changed. Domain scopes overlap, and a domain record is mechanical extraction plus policy analysis rather than a manual article review for every ID.</p>
 <h2>What the grouping model should represent</h2>
 <p>Give each exact ID an identity and explicit variant state, then attach independent functional roles and grouping edges. Derive bank placement from the selected workflow and player preferences. A single category cannot faithfully represent combat gear that is also clue equipment, produce that is also a potion input, or quest-origin items with reusable functions.</p>
 {table(['Axis','Mechanical evidence','Important limit'],[
 ['Identity and variant','Exact Wiki IDs; page/subpage; explicit dose, charge, serving or state metadata.','Never merge IDs or inherit facts from similar names.'],
 ['Equipment and outfits','Exact equipment matches, component lists, local set members and slot order.','Zero bonuses do not mean junk; ammo slot does not imply ammunition.'],
 ['Production stages','Seed/sapling, raw/processed materials, ingredient/tool/output relations.','Recipe title links are candidates until variant-specific inputs and outputs are proved.'],
 ['Activity and collection','Formal clue requirements, reward provenance, structured log-table links.','Quest association and collection provenance do not determine retention or placement.'],
 ['Storage and preference','Exact container state/capacity, costume storage eligibility, account choices.','Storage eligibility is not cosmetic-only status; frequent use is player-dependent.']])}
 <h2>Concrete priorities</h2>{table(['Area','Finding','Grouping recommendation','Evidence'],priorities)}
 <h2>Coverage and grouping inventory</h2>
 {table(['Measure','Count'],[['Named effective IDs',f"{s['counts']['effective_records']:,}"],['Exact single Wiki item-record matches',f"{s['counts']['EXACT_ID_SINGLE']:,}"],['IDs with multiple exact Wiki matches',s['counts']['EXACT_ID_MULTIPLE']],['IDs without an exact Wiki fact',f"{s['counts']['NO_EXACT_ID_FACT']:,}"],['Explicit cache exclusions',s['excluded_cache_records']],['Null/invalid-name omissions',s['omitted_invalid_or_null_name_rows']],['Alternate lookup bucket rows','17,699'],['Effective IDs with literal alternate ID links',f"{s['counts'].get('with_alternate_lookup_link',0):,}"],['Lookup-only IDs without primary item facts',s['counts'].get('lookup_only_unverified',0)],['Fetched Wiki item-version rows','16,888'],['Equipment rows','5,767'],['Recipe rows','7,785'],['Local and separately sourced/proposed groups',g['local_and_sourced_groups']],['Group membership edges',g['group_edges']],['Distinct effective IDs with exact group edges',g['distinct_grouped_effective_ids']],['Recipe workflow edges',f"{g['recipe_workflow_edges']:,}"],['Explicit Wiki version pools',f"{g['wiki_explicit_version_pools']:,}"],['IDs covered by those source version pools',f"{g['wiki_version_pool_distinct_ids']:,}"],['Weak catalog family clusters',f"{g['weak_name_family_clusters']:,}"]])}
 <p>Existing local set/layout families are a baseline, not independently reverified Wiki truth. Newly sourced dose and food groups, proposed material workflows and reviewed gear groups are labeled separately. Recipe pools and name clusters stay candidate evidence.</p>
 <h2>Domain coverage</h2>{table(['Review domain','Rows','Artifacts'],domainrows)}
 <h2>Mechanical review queue</h2>
 {table(['Detector','Signals'],[[esc(k),v] for k,v in s['finding_detector_counts'].items()])}
 <p>{s['mechanical_finding_count']:,} signals affect {s['mechanically_flagged_distinct_items']:,} distinct items. Quest and recipe overlap signals are weaker than direct function evidence. Signal counts must not be summed with domain queues to count defects.</p>
 <h2>Source and method safeguards</h2>
 <ul><li>All exact-ID records were retained: 4,119 matched IDs have no default-version row. Choosing only default versions would silently discard them.</li>
 <li>All 13 multiple-match IDs remain explicit, including clue instances, Echo orb league pages and Keris partisan inside/outside ToA.</li>
 <li>Equipment evidence keeps 5,632 exact page/subpage relationships separate from 142 unique-page fallbacks, covering 5,773 IDs.</li>
 <li>Four partial positive category cases across multiple candidate rows are exposed rather than converted into variant-specific facts.</li>
 <li>Whitespace ID parsing and six Windows UTF-8 title corruptions were corrected; the 16,888 raw and merged source identity keys now agree.</li>
 <li>161 registry IDs outside the effective export also match Wiki records (45 excluded and 116 null-name IDs). They form a separate boundary review, not evidence that exclusions are wrong.</li>
 <li>The alternate Item id bucket was also checked: 661 additional literal ID links lack primary item-infobox facts. Some lookup IDs lose namespace prefixes or refer to construction definitions, so they remain separate guarded evidence.</li>
 <li>No absent category, bonus, Wiki page or bank record is used as proof of absent function. Category positives are page-scoped. The 17,074 unmatched IDs require typed cache relationships or direct variant research before propagation.</li></ul>
 <h2>Deliverables</h2><ul>{''.join('<li>'+link(file,label)+'</li>' for file,label in outputs)}</ul>
 <h2>Validation and reproducibility</h2><p>Fresh current-catalog and preset-tag exports succeeded using the existing Java toolchain. The cached fetch/enrichment/join pipeline, domain builders and grouping consolidation were executed; Python scripts passed compilation checks and full-ID accounting/source-identity invariants passed. The existing Gradle test task returned success with its results up to date; no tests were added.</p>
 <p>Reproduction instructions and research-only code are in <code>tools/research/semantic-grouping-audit/</code>. Raw source packets retain their query, acquisition time and hashes. Bulk item rows lack individual article revisions; that is explicitly weaker than the pinned revisions on reviewed article or local metadata sources.</p>
 <footer>OSRS Wiki facts: CC BY-NC-SA 3.0. Source links and source-specific confidence are retained in the outputs. Local catalog/preset membership is this repository’s original baseline. Generated {esc(g['generated_at'])}.</footer>'''
 css='''body{font:15px/1.55 system-ui,sans-serif;margin:0;color:#233044;background:#f6f8fb}main{max-width:1100px;margin:auto;padding:48px 32px 70px;background:white}h1{font-size:38px;line-height:1.12;margin:12px 0 22px}h2{margin-top:40px;font-size:23px}a{color:#175e9d}p{max-width:95ch}.eyebrow{font-size:12px;letter-spacing:.12em;color:#526785}.lead{font-size:18px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:25px 0}.metrics div{padding:18px;background:#edf3fa;border-radius:10px}.metrics b{font-size:28px;display:block}.metrics span{font-size:13px}table{border-collapse:collapse;width:100%;font-size:13px;margin:18px 0}th,td{text-align:left;vertical-align:top;padding:11px;border:1px solid #dce4ed}th{background:#edf3fa}tr:nth-child(even){background:#fafbfd}footer{margin-top:40px;padding-top:20px;border-top:1px solid #dce4ed;font-size:12px;color:#66758a}@media(max-width:750px){main{padding:25px 15px}.metrics{grid-template-columns:repeat(2,1fr)}table{display:block;overflow:auto}h1{font-size:30px}}'''
 (out/'semantic-grouping-report.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bank Architect semantic grouping audit</title><style>'+css+'</style><main>'+body+'</main></html>',encoding='utf-8')
 print(out/'semantic-grouping-report.html')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--output',type=pathlib.Path,default=ROOT/'tmp/semantic-audit');run(p.parse_args().output)
