import argparse,collections,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]
BASE=ROOT/'tmp/category-certification'
DEFAULT_DECISIONS=BASE/'reviews/transport-v2/decisions.jsonl'
DEFAULT_PACKET=BASE/'reviewer-packets/currency-runes-teleport.jsonl'
DEFAULT_OUT=BASE/'reviews/transport-v2/certificate-rule-review.md'
RULE_NOTES={
 ('CURRENCY','currency'):('Classify exact-ID tokens as currency only when the item can be spent or exchanged for a named service, access, charge, or reward. The group includes explicit normal exchange value and one separately worded discontinued Agility-ticket exception.','Reject quest proof, reward containers, edible prizes, crafting inputs, and tokens with no documented exchange. Quest association does not disqualify repeatable exchange value; mode-limited currency remains mode-specific.'),
 ('RUNE','rune'):('Use exact article mechanics showing the exact item is consumed as a spell rune or direct substitute.','Do not infer from “rune” in name, Wiki categories, recipe backlinks, or a minigame-only display item. A variant’s actual availability/retention can constrain whether it is a bank supply.'),
 ('RUNE','runecrafting-focus'):('Place exact talismans/tiaras that grant altar entry with Runecraft tools, distinct from spellcasting supplies.','An item called tiara is not enough: cosmetic, unobtainable, or non-attuned tiaras do not satisfy the focus rule.'),
 ('RUNE','rune-container'):('Use exact mechanics showing storage or casting from stored spell runes.','Do not conflate an essence pouch or an activity-specific temporary version with a bankable rune-storage tool.'),
 ('RUNE','runecrafting-utility'):('A direct Runecraft production aid, such as a binding necklace that affects combination-rune success, belongs with skilling tools.','The cited mechanic must be an actual production effect, not merely a Runecraft page/category link.'),
 ('TELEPORT','teleport'):('The exact item offers active or rechargeable movement; return travel and network movement count when explicitly documented.','Check exact state and competing primary functions. A teleport mention in trivia, lore, a quest transcript, or an unrelated item effect does not prove this placement.'),
 ('TELEPORT','teleport-tablet'):('The exact tablet is activated/consumed to move the player or another explicitly supported transport target.','Magic tablets that enchant, transform, or heal are not teleport tablets; verify the exact item’s action and destination.'),
 ('TELEPORT','teleport-scroll'):('The exact scroll activates player movement to a named destination.','A scroll-shaped quest document or dummy/selected destination marker is not a transport scroll.'),
 ('TELEPORT','teleport-charge'):('The exact item is consumed to add documented teleport charges to a transport device.','A teleport being mentioned elsewhere on the page does not make a material a charge; require explicit item-to-device charge mechanics.'),
 ('TELEPORT','teleport-container'):('The exact book/container stores and dispatches usable teleport scrolls.','Confirm both the exact empty/filled item version and the storage/dispatch function.'),
 ('TELEPORT','transport-access'):('The exact item is required to use a named player transport system or opens/installs that network.','A quest prop used by an NPC or a blueprint for a separate portal is not player transport access.'),
}
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--decisions',type=Path,default=DEFAULT_DECISIONS);ap.add_argument('--packets',type=Path,default=DEFAULT_PACKET);ap.add_argument('--output',type=Path,default=DEFAULT_OUT);a=ap.parse_args()
 ds=[json.loads(x) for x in a.decisions.read_text(encoding='utf8').splitlines() if x.strip()];ps={x['itemId']:x for x in (json.loads(l) for l in a.packets.read_text(encoding='utf-8-sig').splitlines() if l.strip())}
 cert=[d for d in ds if d['decision']=='certify']; groups=collections.defaultdict(list)
 for d in cert:groups[(d['proposedCategory'],d['proposedSubcategory'])].append(d)
 if len(ds)!=1138 or len(cert)!=343:raise ValueError(f'Frozen v2 totals differ: rows={len(ds)} certificates={len(cert)}')
 md=['# Transport v2 certificate rule review','',f'Inputs: `decisions.jsonl` SHA-256 `{sha(a.decisions)}`; packet SHA-256 `{sha(a.packets)}`. Frozen scope: 1,138 exact IDs; 343 v2 `certify` decisions (30.1% of rows), 105 `revise`, 690 `unresolved`. This packet accounts for every certificate by target category/subcategory. The count is reviewer output, not an independent semantic approval.','', 'The v2 Wiki source gate validated revision pins, source hashes, exact numeric-ID bindings, and cited-text presence. That gate proves source integrity, not that the selected excerpt establishes the semantic predicate. Reusable rules below are therefore review targets; each representative excerpt is literal from the exact item citation in that row.','', '| Target | Count | Rule | Representative exact Wiki evidence | Exceptions / rejection conditions |','|---|---:|---|---|---|']
 rows_json=[]
 for key in sorted(groups):
  rows=sorted(groups[key],key=lambda d:d['itemId']); cat,sub=key; rule,risk=RULE_NOTES[key]
  rep=next((d for d in rows if d.get('evidence') and d['evidence'][0].get('quote')),rows[0]); e=rep['evidence'][0]; quote=e.get('quote','').replace('|','\\|').replace('\n',' ')
  if len(quote)>280:quote=quote[:277].rsplit(' ',1)[0]+'…'
  ref=f"ID {rep['itemId']} {ps[rep['itemId']]['catalogName']}; {e.get('sourceTitle')} rev {e.get('sourceRevision')}; `{e.get('sourceHash')}`: “{quote}”"
  ids=[d['itemId'] for d in rows]
  md.append(f'| `{cat}/{sub}` | {len(rows)} | {rule} | {ref} | {risk} |')
  rows_json.append({'category':cat,'subcategory':sub,'count':len(rows),'itemIds':ids,'rule':rule,'riskAndExceptions':risk,'representative':{'itemId':rep['itemId'],'catalogName':ps[rep['itemId']]['catalogName'],'sourceTitle':e.get('sourceTitle'),'sourceRevision':e.get('sourceRevision'),'source':e.get('source'),'sourceHash':e.get('sourceHash'),'literalQuote':e.get('quote')}})
 md+=['','Totals by top-level assignment: TELEPORT 265, RUNE 43, CURRENCY 35. The 11 rule groups sum to 343; the listed ID arrays in the companion JSON provide row-level accounting.','', 'Independent review flags:', '', '- The generic teleport rule (184 rows) includes items with mixed functions, including wearable equipment and return devices. Evaluate the exact current assignment and primary role where combat, clue, or utility use competes with travel. A valid teleport function alone may not establish primary placement.', '- The rune-focus rule (18 rows) is sensitive to explicit attunement and unobtainable/cosmetic exceptions. Spell runes, pouches, and production helpers are counted separately.', '- The currency rule (35 rows) covers named exchanges and access/charge value; do not extend it to one-off proof tokens, reward containers, ordinary alch value, or crafting inputs.', '- Validate every excerpt for predicate support. The local source audit checks exact item/revision/hash/text, but does not interpret whether the quote proves use, primary role, bank retention, repeatability, or tab choice.', '- Earlier source-selection failures documented by root show why hashes and a matching keyword are insufficient: excerpts from transcript/footer/trivia or reward history must not count as functional evidence. The v2 snapshot should be reopened if any row’s selected quote has that defect.','', 'Focused exact-ID checks requested for manual review:', '', '- Ring of coins (20017) is v2 `revise` to `CLUE/cosmetic`: the exact page/revision 15325243 says it “can change the model of the player to look like a pile of [[coins]].” This is a disguise effect, not spendable coin value. Its note (20018) and placeholder (20019) have directed exact cache edges to 20017, but remain unresolved as raw-ID classifications because bank withdrawal-note conversion and placeholder canonicalization are runtime representation facts, not permission to propagate the canonical category onto the raw aliases. The note is withdrawal-only in the sense that depositing it converts it to the unnoted item.', '- Disk of returning (981) is v2 `certify` as `TELEPORT/teleport`: the exact page/revision 15306241 says activation teleports the player into the Blackhole and a second activation returns the player to the Dwarven Mine. That supports a two-way return transport function, not merely a title match.', '- These cases do not resolve every similarly named morph item, note, placeholder, or teleport. Each numeric ID still needs its own exact article/variant or typed directed identity evidence.','']
 a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text('\n'.join(md),encoding='utf8')
 machine=a.output.with_suffix('.json');machine.write_text(json.dumps({'sourceDecisionSha256':'sha256:'+sha(a.decisions),'sourcePacketSha256':'sha256:'+sha(a.packets),'rowCount':len(ds),'certificateCount':len(cert),'groups':rows_json},ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf8')
 print(f'Wrote {a.output} and {machine}; {len(cert)} certificates in {len(groups)} rule groups')
if __name__=='__main__':main()
